create table band (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id));
create table event (id bigint generated by default as identity (start with 1), comment varchar(255), nb_stars integer, img_url varchar(255), title varchar(255), primary key (id));
create table event_bands (event_id bigint not null, bands_id bigint not null, primary key (event_id, bands_id));
alter table event_bands add constraint FK551i3sllw1wj7ex6nir16blsm foreign key (bands_id) references band;
alter table event_bands add constraint FKs4xm7q8i3uxvaiswj1c35nnxw foreign key (event_id) references event;